all: point.o week-3_labs.o
	g++ point.o week-3_labs.o -o prog
	
point.o: point.cpp point.hpp
	g++ -c point.cpp
	
week-3_labs.o: week-3_labs.cpp
	g++ -c week-3_labs.cpp
	
run:
	./prog
#./prog.exe if Windows/Cygwin

clean:
	rm *.o prog
# rm *.o prog.exe if Windows/Cygwin

#structure
#target: [dependencies list ...]
#	commands #starts with a tabulation
