all: point.o main.o
	g++ point.o main.o -o prog
	
point.o: point.cpp point.hpp
	g++ -c point.cpp
	
main.o: main.cpp
	g++ -c main.cpp
	
run:
	./prog
#./prog.exe if Windows/Cygwin

clean:
	rm *.o prog
# rm *.o prog.exe if Windows/Cygwin

#structure
#target: [dependencies list ...]
#	commands #starts with a tabulation
