all: point.o main.o
	g++ week-1_lab.o week-1_lab.o -o prog
	
point.o: week-1_lab.cpp classpoint.hpp
	g++ -c week-1_lab.cpp
	
main.o: week-2_lab.cpp
	g++ -c week-2_lab.cpp
	
run:
	./prog
#./prog.exe if Windows/Cygwin

clean:
	rm *.o prog
# rm *.o prog.exe if Windows/Cygwin

#structure
#target: [dependencies list ...]
#	commands #starts with a tabulation
